[tool.poetry]
name = "osr-stuff"
version = "0.1.0"
description = ""
authors = ["Andrew Herbig <notandrewherbig@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pygame = "^2.0.1"
recordclass = "^0.14.3"
Pillow = "^8.2.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.1"
pre-commit = "^2.12.1"
pyupgrade = "^2.13.0"
isort = "^5.8.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
